### PR TITLE
Upgrade cython==0.29.24 to work with Python 3.10

### PR DESCRIPTION
**Pull request by mwtoews**
[Attempts](https://github.com/shapely/shapely-wheels/pull/10/commits/d8700bbee937d515a197353452b0651783abc23c) to build Shapely for Python 3.10 on Windows [flopped with an error](https://ci.appveyor.com/project/frsci/shapely-wheels/builds/41413927/job/q8r6r6w36ae35527#L2172):
> _speedups.obj : error LNK2001: unresolved external symbol _PyGen_Send

which is described at https://github.com/cython/cython/issues/3876

This was resolved as of cython version 0.29.22, but this PR uses the latest cython update in the 0.29.x series.

Xref #1215 and https://github.com/shapely/shapely-wheels/pull/10

### CODE REVIEW

**Review by jorisvandenbossche — APPROVED** [review]
Looks good to me, thanks!

(assuming CI passes)
