### ISSUE TITLE
C extension could not be compiled, speedups are not enabled, for shapely 1.7 with system-provided GEOS and --no-binary pip install

### ISSUE THREAD

**Issue by akursar** [Toblerity/Shapely#965]
## Expected behavior and actual behavior.

When libgeos/numpy is installed, I expect shapely installation to compile extensions and enable speedups. This happened on 1.6.4.post2 but it does not seem to work with 1.7.0. Instead, I see `error: too many arguments to function ‘PyCode_New’` errors during the install which I cannot seem to work around. I thought I might have to pin a cython version but that seemed to be a dead end.

## Steps to reproduce the problem.

This dockerfile works:

    FROM python:3.8
    RUN apt-get update && apt-get install -y libgeos-dev
    RUN pip install numpy
    RUN pip install --no-binary shapely shapely==1.6.4.post2 -v
    RUN python -c "from shapely import speedups; assert speedups.enabled"

but this one does not

    FROM python:3.8
    RUN apt-get update && apt-get install -y libgeos-dev
    RUN pip install numpy
    RUN pip install --no-binary shapely shapely==1.7.0 -v
    RUN python -c "from shapely import speedups; assert speedups.enabled"

1.7a1 works but 1.7a2 does not.

## Operating system

I'm on a mac but am exclusively working in docker with python:3.8 image described above.

## Shapely version and provenance

1.7.0 installed with pip

**Comment by sgillies** [comment]
@akursar cython is also a build dependency of shapely and it looks like your version is old (https://github.com/cython/cython/issues/2938). I'm successfully building shapely with speedups for Python 3.8: https://pypi.org/project/Shapely/#files.  Change `pip install numpy` to `pip install cython numpy` and that should do it.

**Comment by akursar** [comment]
Thanks @sgillies , but I've tried that without success. Installing latest cython ( 0.29.21) produces the same error message, as does pinning cython to the version in shapely's requirements-dev.txt (0.29.14) in that simple Dockerfile. The error message is:

    shapely/speedups/_speedups.c:318:11: error: too many arguments to function ‘PyCode_New’

While googling, I came across a few examples like this: https://twistedmatrix.com/trac/ticket/9674 ("raiser.c is busted again on cpython" "Fail to compile, needs regenerating.") where a similar message prompted the regeneration of a *.c file to be compatible with newer cython. However, I'm out of my league here. I'm not sure where that _speedups.c file is coming from if that's indeed the issue, or how to go about working around. Does that help at all?

**Comment by sgillies** [comment]
@akursar thanks for the follow up! I've discovered what the problem is: I accidentally generated the shapely 1.7.0 source distribution using Cython 0.29.10 (you can see this at the top of _speedups.c) and the Python 3.8 issue wasn't fixed until 0.29.11 or later (https://cython.readthedocs.io/en/latest/src/changes.html#id40). Instead of making a 1.7.0 post-release, I'm going to speed up the release of 1.7.1.
